framework: jest
postMerge: 
  pattern: 
    - "**/*.test.js"
postRun: 
  command: 
    - "node --version"  
preMerge: 
  pattern: 
    - "**/*.test.js"
preRun: 
  command:
    - npm install -g npm@8.12.1
    - npm ci    
