#1
framework: jest
version: 1.2.0 
postMerge: 
  pattern: 
    - "**/*.test.js"
postRun: 
  command: 
    - "node --version"  
preMerge: 
  pattern: 
    - "**/*.test.js"
preRun: 
  command:
    - npm ci    
